[server]
# Configurações para deploy no Render
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Desabilitar coleta de estatísticas
gatherUsageStats = false

[theme]
# Tema personalizado
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
